client:
  instances:
    greeting:
      url: http://localhost:8091/greeting
    ping:
      url: http://localhost:8091/ping
    fail:
      url: http://localhost:8091/fail

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  retry:
    instances:
      twice:
        maxAttempts: 3
        waitDuration: 200ms
  circuitbreaker:
    instances:
      always:
        minimumNumberOfCalls: 3

spring:
  application:
    name: hello-resilience-client

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram.resilience4j.circuitbreaker.calls: true
    tags:
      application: ${spring.application.name}

