client:
  instances:
    greeting:
      url: http://localhost:8091/greeting
    ping:
      url: http://localhost:8091/ping

feign:
  circuitbreaker:
    enabled: true

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"